### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by tarkhil** [intlify/vite-vue-i18n-starter#2]
After git clone, npm install and npm dev it compiles without a problem but runtime error

```
  TypeError: t is not a function
      at /usr/home/tarkhil/tmp/vite-vue-i18n-starter/node_modules/vite/dist/node/transform.js:60:38
      at processTicksAndRejections (node:internal/process/task_queues:93:5)
      at async /usr/home/tarkhil/tmp/vite-vue-i18n-starter/node_modules/vite/dist/node/server/serverPluginHtml.js:43:9
      at async /usr/home/tarkhil/tmp/vite-vue-i18n-starter/node_modules/vite/dist/node/server/serverPluginModuleRewrite.js:52:9
      at async /usr/home/tarkhil/tmp/vite-vue-i18n-starter/node_modules/vite/dist/node/server/serverPluginSourceMap.js:26:9
```

**Comment by kazupon** [comment]
Fixed

**Comment by tarkhil** [comment]
Next problem emerged
```
[vite] failed to load config from /usr/home/tarkhil/tmp/vite-vue-i18n-starter/vite.config.ts:
TypeError: vitePluginVueI18n.pluginI18n is not a function
    at Object.<anonymous> (/usr/home/tarkhil/tmp/vite-vue-i18n-starter/vite.config.ts:11:23)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.require.extensions.<computed> [as .ts] (/usr/home/tarkhil/tmp/vite-vue-i18n-starter/node_modules/vite/dist/node/config.js:118:20)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Module.require (node:internal/modules/cjs/loader:991:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at loadConfigFromBundledFile (/usr/home/tarkhil/tmp/vite-vue-i18n-starter/node_modules/vite/dist/node/config.js:125:17)
    at Object.resolveConfig (/usr/home/tarkhil/tmp/vite-vue-i18n-starter/node_modules/vite/dist/node/config.js:78:32)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vite-vue-i18n-starter@0.0.0 dev: `vite`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vite-vue-i18n-starter@0.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tarkhil/.npm/_logs/2020-12-24T23_18_26_043Z-debug.log
```

**Comment by kazupon** [comment]
Please, try to `npm install` or `yarn`.
